# Global settings
set -g mouse on
setw -g mode-keys vi
#
# Options to make tmux more pleasant
set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"

# Global key-binds
unbind r
bind r source-file ~/.config/tmux/tmux.conf

set-option -g allow-rename off
set-option -g automatic-rename off

set -g renumber-windows on
set-option -g status-position bottom

# Navigation key bind
bind-key h select-pane -R
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -L

# Load tmux-power theme, power-like them. very cool!
# set -g @plugin 'wfxr/tmux-power'
# set -g @tmux_power_theme 'coral'
# -------------------------------

# Theme config
# -------------------------------
# Nord theme
# set -g @plugin "arcticicestudio/nord-tmux"
# set -g @nord_tmux_no_patched_font "0"
#
# Rose-pine theme
set -g @plugin 'rose-pine/tmux'
set -g @rose_pine_variant 'dawn'
# -------------------------------

set -g @rose_pine_status_right_append_section ' | CPU: #{cpu_percentage} | %a %h-%d %H:%M '

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'
